apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: free5gc-build:v3.1.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "cd webconsole && ./bin/webconsole -c ../config/webuicfg.yaml"]
          ports:
            - name: webui
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: webui-config
              mountPath: /root/free5gc/config/webuicfg.yaml
              subPath: webuicfg.yaml
      volumes:
        - name: webui-config
          configMap:
            name: webui
