apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  labels:
    app: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"192.168.2.9\"]"
    spec:
      containers:
        - name: udr
          image: free5gc-build:v3.1.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "./bin/udr -c ./config/udrcfg.yaml"]
          stdin: true
          tty: true
          volumeMounts:
            - name: udr-config
              mountPath: /root/free5gc/config/udrcfg.yaml
              subPath: udrcfg.yaml
      volumes:
        - name: udr-config
          configMap:
            name: udr

